### ISSUE TITLE
Remember previously selected options

### ISSUE THREAD

**Issue by DeltaCopy** [arcolinux/sofirem#1]
The settings which appear in the top right hand corner should be preserved after a restart.
Save settings to a conf file, in order for the app to remember the users previously selected options.

**Comment by DeltaCopy** [comment]
The initial approach is to have a defaults directory inside.
```/usr/share/sofirem/defaults```

Inside there have a yaml file called ```sofirem.yaml```

This holds all default app settings.

Format:

```yaml
- name: "Display Package Versions"
  description: "Show package version labels alongside the package description"
  enabled: False

- name: "Display Package Progress"
  description: "Show the package install/uninstall progress window"
  enabled: False
```

This file is copied over to ```$HOME/.config/sofirem/sofirem.yaml```
On app load this file is read into memory, processed and the UI is updated appropriately based on the settings.
On app close this file is updated based on the last options selected.
